/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author jpaula
 */
public class AsignarTroquel extends javax.swing.JFrame {

    /**
     * Creates new form At
     */
    public AsignarTroquel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        solicitud = new javax.swing.JTextField();
        grupo = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        cliente = new javax.swing.JTextField();
        producto = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        troquel = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        imagentrasera = new javax.swing.JTextField();
        imagenfrontal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        codigoproducto = new javax.swing.JTextField();
        componente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo Producto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cliente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 60, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Solicitud");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 20));

        solicitud.setEditable(false);
        solicitud.setBackground(new java.awt.Color(204, 204, 204));
        solicitud.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        solicitud.setForeground(new java.awt.Color(255, 255, 255));
        solicitud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(solicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 180, 25));

        grupo.setEditable(false);
        grupo.setBackground(new java.awt.Color(204, 204, 204));
        grupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        grupo.setForeground(new java.awt.Color(255, 255, 255));
        grupo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 40, 25));

        codigo.setEditable(false);
        codigo.setBackground(new java.awt.Color(204, 204, 204));
        codigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigo.setForeground(new java.awt.Color(255, 255, 255));
        codigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 100, 25));

        cliente.setEditable(false);
        cliente.setBackground(new java.awt.Color(204, 204, 204));
        cliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cliente.setForeground(new java.awt.Color(255, 255, 255));
        cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 270, 25));

        producto.setEditable(false);
        producto.setBackground(new java.awt.Color(204, 204, 204));
        producto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        producto.setForeground(new java.awt.Color(255, 255, 255));
        producto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 330, 25));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Troquel");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 235, -1, -1));

        troquel.setEditable(false);
        troquel.setBackground(new java.awt.Color(204, 204, 204));
        troquel.setForeground(new java.awt.Color(255, 255, 255));
        troquel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(troquel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 234, 120, 25));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("IMAGEN FRONTAL");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("IMAGEN TRASERA");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, -1, -1));

        imagentrasera.setEditable(false);
        imagentrasera.setBackground(new java.awt.Color(255, 255, 255));
        imagentrasera.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(imagentrasera, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 550, 330));

        imagenfrontal.setEditable(false);
        imagenfrontal.setBackground(new java.awt.Color(255, 255, 255));
        imagenfrontal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(imagenfrontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 550, 330));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, -1, -1));

        fecha.setEditable(false);
        fecha.setBackground(new java.awt.Color(204, 204, 204));
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 140, 110, 25));

        logo.setBackground(new java.awt.Color(102, 102, 102));
        logo.setForeground(new java.awt.Color(102, 102, 102));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGO CARTONES full.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 310, 100));

        jToggleButton2.setBackground(new java.awt.Color(102, 102, 102));
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar-button.png"))); // NOI18N
        jToggleButton2.setSelected(true);
        jToggleButton2.setBorder(null);
        jToggleButton2.setBorderPainted(false);
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 700, 45, 45));

        codigoproducto.setEditable(false);
        codigoproducto.setBackground(new java.awt.Color(204, 204, 204));
        codigoproducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoproducto.setForeground(new java.awt.Color(255, 255, 255));
        codigoproducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(codigoproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 60, 25));

        componente.setEditable(false);
        componente.setBackground(new java.awt.Color(204, 204, 204));
        componente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        componente.setForeground(new java.awt.Color(255, 255, 255));
        componente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(componente, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 200, 30, 25));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarTroquel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarTroquel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarTroquel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarTroquel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsignarTroquel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cliente;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField codigoproducto;
    private javax.swing.JTextField componente;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField grupo;
    private javax.swing.JTextField imagenfrontal;
    private javax.swing.JTextField imagentrasera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField producto;
    private javax.swing.JTextField solicitud;
    private javax.swing.JTextField troquel;
    // End of variables declaration//GEN-END:variables
}
