/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author jpaula
 */
public class PendientePreprensa extends javax.swing.JFrame {

    /**
     * Creates new form pp
     */
    public PendientePreprensa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        procesosdiarios = new javax.swing.JTabbedPane();
        pendientemuestra = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        nosolicitudmuestra = new javax.swing.JTable();
        jScrollPane13 = new javax.swing.JScrollPane();
        nombreclientemuestra = new javax.swing.JTable();
        jScrollPane14 = new javax.swing.JScrollPane();
        descripciondeproductomuestra = new javax.swing.JTable();
        jScrollPane15 = new javax.swing.JScrollPane();
        fechamuestra = new javax.swing.JTable();
        pendientearte = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        nosolicitudarte = new javax.swing.JTable();
        jScrollPane17 = new javax.swing.JScrollPane();
        nombreclientearte = new javax.swing.JTable();
        jScrollPane18 = new javax.swing.JScrollPane();
        descripciondeproductoarte = new javax.swing.JTable();
        jScrollPane19 = new javax.swing.JScrollPane();
        fechaarte = new javax.swing.JTable();
        pendientedesellos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pendientearte1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        pendientearte2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        pendientearte3 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        pendientearte5 = new javax.swing.JTable();
        pendientedetroquel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        pendientearte4 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        pendientearte6 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        pendientearte7 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        pendientearte8 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        imprimir = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        procesosdiarios.setBackground(new java.awt.Color(153, 153, 153));
        procesosdiarios.setForeground(new java.awt.Color(0, 0, 0));
        procesosdiarios.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        procesosdiarios.setAutoscrolls(true);
        procesosdiarios.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        pendientemuestra.setBackground(new java.awt.Color(153, 153, 153));
        pendientemuestra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nosolicitudmuestra.setAutoCreateRowSorter(true);
        nosolicitudmuestra.setBackground(new java.awt.Color(204, 204, 204));
        nosolicitudmuestra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nosolicitudmuestra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "No. Solicitud"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        nosolicitudmuestra.setGridColor(new java.awt.Color(102, 102, 102));
        nosolicitudmuestra.setRowHeight(25);
        nosolicitudmuestra.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane12.setViewportView(nosolicitudmuestra);

        pendientemuestra.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 320));

        nombreclientemuestra.setAutoCreateRowSorter(true);
        nombreclientemuestra.setBackground(new java.awt.Color(204, 204, 204));
        nombreclientemuestra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nombreclientemuestra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre del Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        nombreclientemuestra.setGridColor(new java.awt.Color(102, 102, 102));
        nombreclientemuestra.setRowHeight(25);
        nombreclientemuestra.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane13.setViewportView(nombreclientemuestra);

        pendientemuestra.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 370, 320));

        descripciondeproductomuestra.setAutoCreateRowSorter(true);
        descripciondeproductomuestra.setBackground(new java.awt.Color(204, 204, 204));
        descripciondeproductomuestra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        descripciondeproductomuestra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Descripcion del Producto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        descripciondeproductomuestra.setGridColor(new java.awt.Color(102, 102, 102));
        descripciondeproductomuestra.setRowHeight(25);
        descripciondeproductomuestra.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane14.setViewportView(descripciondeproductomuestra);

        pendientemuestra.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 340, 320));

        fechamuestra.setAutoCreateRowSorter(true);
        fechamuestra.setBackground(new java.awt.Color(204, 204, 204));
        fechamuestra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fechamuestra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fechamuestra.setGridColor(new java.awt.Color(102, 102, 102));
        fechamuestra.setRowHeight(25);
        fechamuestra.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane15.setViewportView(fechamuestra);

        pendientemuestra.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 74, 320));

        procesosdiarios.addTab("PENDIENTE DE MUESTRA", pendientemuestra);

        pendientearte.setBackground(new java.awt.Color(153, 153, 153));
        pendientearte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nosolicitudarte.setAutoCreateRowSorter(true);
        nosolicitudarte.setBackground(new java.awt.Color(204, 204, 204));
        nosolicitudarte.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nosolicitudarte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "No. Solicitud"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        nosolicitudarte.setGridColor(new java.awt.Color(102, 102, 102));
        nosolicitudarte.setRowHeight(25);
        nosolicitudarte.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane16.setViewportView(nosolicitudarte);

        pendientearte.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 320));

        nombreclientearte.setAutoCreateRowSorter(true);
        nombreclientearte.setBackground(new java.awt.Color(204, 204, 204));
        nombreclientearte.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nombreclientearte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre del Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        nombreclientearte.setGridColor(new java.awt.Color(102, 102, 102));
        nombreclientearte.setRowHeight(25);
        nombreclientearte.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane17.setViewportView(nombreclientearte);

        pendientearte.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 370, 320));

        descripciondeproductoarte.setAutoCreateRowSorter(true);
        descripciondeproductoarte.setBackground(new java.awt.Color(204, 204, 204));
        descripciondeproductoarte.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        descripciondeproductoarte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Descripcion del Producto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        descripciondeproductoarte.setGridColor(new java.awt.Color(102, 102, 102));
        descripciondeproductoarte.setRowHeight(25);
        descripciondeproductoarte.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane18.setViewportView(descripciondeproductoarte);

        pendientearte.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 340, 320));

        fechaarte.setAutoCreateRowSorter(true);
        fechaarte.setBackground(new java.awt.Color(204, 204, 204));
        fechaarte.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fechaarte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fechaarte.setGridColor(new java.awt.Color(102, 102, 102));
        fechaarte.setRowHeight(25);
        fechaarte.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane19.setViewportView(fechaarte);

        pendientearte.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 74, 320));

        procesosdiarios.addTab("PENDIENTE DE ARTE", pendientearte);

        pendientedesellos.setBackground(new java.awt.Color(153, 153, 153));
        pendientedesellos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pendientearte1.setAutoCreateRowSorter(true);
        pendientearte1.setBackground(new java.awt.Color(204, 204, 204));
        pendientearte1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pendientearte1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Descripcion del Producto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pendientearte1.setGridColor(new java.awt.Color(102, 102, 102));
        pendientearte1.setRowHeight(25);
        pendientearte1.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane3.setViewportView(pendientearte1);

        pendientedesellos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 210, 320));

        pendientearte2.setAutoCreateRowSorter(true);
        pendientearte2.setBackground(new java.awt.Color(204, 204, 204));
        pendientearte2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pendientearte2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pendientearte2.setGridColor(new java.awt.Color(102, 102, 102));
        pendientearte2.setRowHeight(25);
        pendientearte2.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane4.setViewportView(pendientearte2);

        pendientedesellos.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 30, 100, 320));

        pendientearte3.setAutoCreateRowSorter(true);
        pendientearte3.setBackground(new java.awt.Color(204, 204, 204));
        pendientearte3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pendientearte3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre del Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pendientearte3.setGridColor(new java.awt.Color(102, 102, 102));
        pendientearte3.setRowHeight(25);
        pendientearte3.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane5.setViewportView(pendientearte3);

        pendientedesellos.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 390, 320));

        pendientearte5.setAutoCreateRowSorter(true);
        pendientearte5.setBackground(new java.awt.Color(204, 204, 204));
        pendientearte5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pendientearte5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No. Solicitud", "No. Solicitud A"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pendientearte5.setGridColor(new java.awt.Color(102, 102, 102));
        pendientearte5.setRowHeight(25);
        pendientearte5.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane7.setViewportView(pendientearte5);

        pendientedesellos.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 320));

        procesosdiarios.addTab("PENDIENTE DE SELLOS", pendientedesellos);

        pendientedetroquel.setBackground(new java.awt.Color(153, 153, 153));
        pendientedetroquel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pendientearte4.setAutoCreateRowSorter(true);
        pendientearte4.setBackground(new java.awt.Color(204, 204, 204));
        pendientearte4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pendientearte4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Descripcion del Producto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pendientearte4.setGridColor(new java.awt.Color(102, 102, 102));
        pendientearte4.setRowHeight(25);
        pendientearte4.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane6.setViewportView(pendientearte4);

        pendientedetroquel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 210, 320));

        pendientearte6.setAutoCreateRowSorter(true);
        pendientearte6.setBackground(new java.awt.Color(204, 204, 204));
        pendientearte6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pendientearte6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pendientearte6.setGridColor(new java.awt.Color(102, 102, 102));
        pendientearte6.setRowHeight(25);
        pendientearte6.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane8.setViewportView(pendientearte6);

        pendientedetroquel.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 30, 100, 320));

        pendientearte7.setAutoCreateRowSorter(true);
        pendientearte7.setBackground(new java.awt.Color(204, 204, 204));
        pendientearte7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pendientearte7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre del Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pendientearte7.setGridColor(new java.awt.Color(102, 102, 102));
        pendientearte7.setRowHeight(25);
        pendientearte7.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane9.setViewportView(pendientearte7);

        pendientedetroquel.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 390, 320));

        pendientearte8.setAutoCreateRowSorter(true);
        pendientearte8.setBackground(new java.awt.Color(204, 204, 204));
        pendientearte8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pendientearte8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No. Solicitud", "No. Solicitud A"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pendientearte8.setGridColor(new java.awt.Color(102, 102, 102));
        pendientearte8.setRowHeight(25);
        pendientearte8.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane10.setViewportView(pendientearte8);

        pendientedetroquel.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 320));

        procesosdiarios.addTab("PENDIENTE DE TROQUEL", pendientedetroquel);

        jPanel1.add(procesosdiarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 920, 380));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pendiente de Procesos Diarios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        imprimir.setText("Imprimir");
        jPanel1.add(imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 85, -1));

        salvar.setText("Salvar");
        jPanel1.add(salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 85, -1));

        cancelar.setText("Cancelar");
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 85, -1));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 480, 85, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        Preprensa preprensa = new Preprensa();
           preprensa.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendientePreprensa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendientePreprensa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendientePreprensa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendientePreprensa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendientePreprensa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JTable descripciondeproductoarte;
    private javax.swing.JTable descripciondeproductomuestra;
    private javax.swing.JTable fechaarte;
    private javax.swing.JTable fechamuestra;
    private javax.swing.JButton imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable nombreclientearte;
    private javax.swing.JTable nombreclientemuestra;
    private javax.swing.JTable nosolicitudarte;
    private javax.swing.JTable nosolicitudmuestra;
    private javax.swing.JPanel pendientearte;
    private javax.swing.JTable pendientearte1;
    private javax.swing.JTable pendientearte2;
    private javax.swing.JTable pendientearte3;
    private javax.swing.JTable pendientearte4;
    private javax.swing.JTable pendientearte5;
    private javax.swing.JTable pendientearte6;
    private javax.swing.JTable pendientearte7;
    private javax.swing.JTable pendientearte8;
    private javax.swing.JPanel pendientedesellos;
    private javax.swing.JPanel pendientedetroquel;
    private javax.swing.JPanel pendientemuestra;
    private javax.swing.JTabbedPane procesosdiarios;
    private javax.swing.JButton salir;
    private javax.swing.JButton salvar;
    // End of variables declaration//GEN-END:variables
}
