/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author jpaula
 */
public class PendienteReparaciondeSellos extends javax.swing.JFrame {

    /**
     * Creates new form PR
     */
    public PendienteReparaciondeSellos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        procesosdiarios = new javax.swing.JTabbedPane();
        pendientedesellos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pendientearte1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        pendientearte2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        pendientearte3 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        pendientearte5 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        imprimir = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1090, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        procesosdiarios.setBackground(new java.awt.Color(153, 153, 153));
        procesosdiarios.setForeground(new java.awt.Color(0, 0, 0));
        procesosdiarios.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        procesosdiarios.setAutoscrolls(true);
        procesosdiarios.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        pendientedesellos.setBackground(new java.awt.Color(153, 153, 153));
        pendientedesellos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pendientearte1.setAutoCreateRowSorter(true);
        pendientearte1.setBackground(new java.awt.Color(204, 204, 204));
        pendientearte1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pendientearte1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Descripcion del Producto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pendientearte1.setGridColor(new java.awt.Color(102, 102, 102));
        pendientearte1.setRowHeight(25);
        pendientearte1.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane3.setViewportView(pendientearte1);

        pendientedesellos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 210, 320));

        pendientearte2.setAutoCreateRowSorter(true);
        pendientearte2.setBackground(new java.awt.Color(204, 204, 204));
        pendientearte2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pendientearte2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pendientearte2.setGridColor(new java.awt.Color(102, 102, 102));
        pendientearte2.setRowHeight(25);
        pendientearte2.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane4.setViewportView(pendientearte2);

        pendientedesellos.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 30, 100, 320));

        pendientearte3.setAutoCreateRowSorter(true);
        pendientearte3.setBackground(new java.awt.Color(204, 204, 204));
        pendientearte3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pendientearte3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre del Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pendientearte3.setGridColor(new java.awt.Color(102, 102, 102));
        pendientearte3.setRowHeight(25);
        pendientearte3.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane5.setViewportView(pendientearte3);

        pendientedesellos.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 390, 320));

        pendientearte5.setAutoCreateRowSorter(true);
        pendientearte5.setBackground(new java.awt.Color(204, 204, 204));
        pendientearte5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pendientearte5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No. Solicitud", "No. Solicitud A"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pendientearte5.setGridColor(new java.awt.Color(102, 102, 102));
        pendientearte5.setRowHeight(25);
        pendientearte5.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane7.setViewportView(pendientearte5);

        pendientedesellos.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 320));

        procesosdiarios.addTab("PENDIENTE DE SELLOS EN REPARACION", pendientedesellos);

        jPanel1.add(procesosdiarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 920, 380));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pendiente de Procesos Diarios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 480, 85, -1));

        imprimir.setText("Imprimir");
        jPanel1.add(imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 85, -1));

        salvar.setText("Salvar");
        jPanel1.add(salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 85, -1));

        cancelar.setText("Cancelar");
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 85, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
       Preprensa preprensa = new Preprensa();
           preprensa.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendienteReparaciondeSellos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendienteReparaciondeSellos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendienteReparaciondeSellos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendienteReparaciondeSellos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendienteReparaciondeSellos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable pendientearte1;
    private javax.swing.JTable pendientearte2;
    private javax.swing.JTable pendientearte3;
    private javax.swing.JTable pendientearte5;
    private javax.swing.JPanel pendientedesellos;
    private javax.swing.JTabbedPane procesosdiarios;
    private javax.swing.JButton salir;
    private javax.swing.JButton salvar;
    // End of variables declaration//GEN-END:variables
}
