/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.PopupMenu;
import javax.swing.JFrame;

/**
 *
 * @author jpaula
 */
public class Preprensa extends javax.swing.JFrame {

    /**
     * Creates new form Preprensa
     */
    public Preprensa() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        desktopprocesosdiarios.setVisible(false);
        desktopreportes.setVisible(false);
        desktopproduccion.setVisible(false);
        desktopsolicitudes.setVisible(false);
        desktoreimpresionsolicitudes.setVisible(false);
        desktoplogo.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        procesosdiarios = new rsbuttom.RSButtonMetro();
        reportes = new rsbuttom.RSButtonMetro();
        produccion = new rsbuttom.RSButtonMetro();
        jLabel1 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        desktoplogo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        desktopsolicitudes = new javax.swing.JPanel();
        solicitudmuestra = new rsbuttom.RSButtonMetro();
        solicitudarte = new rsbuttom.RSButtonMetro();
        solicitudtroqueles = new rsbuttom.RSButtonMetro();
        solicitudsellos = new rsbuttom.RSButtonMetro();
        solicitudarteviejos = new rsbuttom.RSButtonMetro();
        desktopprocesosdiarios = new javax.swing.JPanel();
        pendientepreprensa = new rsbuttom.RSButtonMetro();
        solicituddearte = new rsbuttom.RSButtonMetro();
        asignartroquel = new rsbuttom.RSButtonMetro();
        creacionprinmaster = new rsbuttom.RSButtonMetro();
        solicitudes = new rsbuttom.RSButtonMetro();
        revision = new rsbuttom.RSButtonMetro();
        desktopreportes = new javax.swing.JPanel();
        reportetrabajosdepreprensapormes = new rsbuttom.RSButtonMetro();
        reportependientedepreprensa = new rsbuttom.RSButtonMetro();
        reportependientedereparacion = new rsbuttom.RSButtonMetro();
        reporteprintmaster = new rsbuttom.RSButtonMetro();
        reportereimpresiondesolicitudes = new rsbuttom.RSButtonMetro();
        desktopproduccion = new javax.swing.JPanel();
        solicituddemuestra4 = new rsbuttom.RSButtonMetro();
        desktoreimpresionsolicitudes = new javax.swing.JPanel();
        solicitudmuestra1 = new rsbuttom.RSButtonMetro();
        solicitudarte1 = new rsbuttom.RSButtonMetro();
        solicitudtroqueles1 = new rsbuttom.RSButtonMetro();
        solicitudsellos1 = new rsbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(958, 669));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir.png"))); // NOI18N
        jButton5.setText("Salir");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, -1, -1));

        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        procesosdiarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/procesosdiarios.png"))); // NOI18N
        procesosdiarios.setText("Procesos Diarios");
        procesosdiarios.setColorHover(new java.awt.Color(102, 102, 102));
        procesosdiarios.setColorNormal(new java.awt.Color(51, 51, 51));
        procesosdiarios.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        procesosdiarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        procesosdiarios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        procesosdiarios.setIconTextGap(10);
        procesosdiarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                procesosdiariosMouseClicked(evt);
            }
        });
        procesosdiarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesosdiariosActionPerformed(evt);
            }
        });
        menu.add(procesosdiarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 110, 220, 50));

        reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Reportes_1.png"))); // NOI18N
        reportes.setText("Reportes");
        reportes.setColorHover(new java.awt.Color(102, 102, 102));
        reportes.setColorNormal(new java.awt.Color(51, 51, 51));
        reportes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reportes.setIconTextGap(10);
        reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportesMouseClicked(evt);
            }
        });
        reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesActionPerformed(evt);
            }
        });
        menu.add(reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 170, 220, 50));

        produccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/produccion.png"))); // NOI18N
        produccion.setText("Producción");
        produccion.setColorHover(new java.awt.Color(102, 102, 102));
        produccion.setColorNormal(new java.awt.Color(51, 51, 51));
        produccion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        produccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        produccion.setIconTextGap(10);
        produccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produccionMouseClicked(evt);
            }
        });
        produccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produccionActionPerformed(evt);
            }
        });
        menu.add(produccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 230, 220, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo-preprensa.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 700));

        jInternalFrame1.setVisible(true);
        menu.add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 560, 220));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 260, 700));

        desktoplogo.setBackground(new java.awt.Color(51, 51, 51));
        desktoplogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGO CARTONES full.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        desktoplogo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 310, 130));

        getContentPane().add(desktoplogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 700, 670));

        desktopsolicitudes.setBackground(new java.awt.Color(102, 102, 102));
        desktopsolicitudes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        solicitudmuestra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/solicitud_muestra.png"))); // NOI18N
        solicitudmuestra.setColorHover(new java.awt.Color(51, 51, 51));
        solicitudmuestra.setColorNormal(new java.awt.Color(102, 102, 102));
        solicitudmuestra.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        solicitudmuestra.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        solicitudmuestra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        solicitudmuestra.setIconTextGap(15);
        solicitudmuestra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                solicitudmuestraMouseClicked(evt);
            }
        });
        solicitudmuestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitudmuestraActionPerformed(evt);
            }
        });
        desktopsolicitudes.add(solicitudmuestra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 200, 220));

        solicitudarte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/solicitud_arte.png"))); // NOI18N
        solicitudarte.setColorHover(new java.awt.Color(51, 51, 51));
        solicitudarte.setColorNormal(new java.awt.Color(102, 102, 102));
        solicitudarte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        solicitudarte.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        solicitudarte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        solicitudarte.setIconTextGap(15);
        solicitudarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitudarteActionPerformed(evt);
            }
        });
        desktopsolicitudes.add(solicitudarte, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 60, 200, 220));

        solicitudtroqueles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/solicitudtroquel.png"))); // NOI18N
        solicitudtroqueles.setColorHover(new java.awt.Color(51, 51, 51));
        solicitudtroqueles.setColorNormal(new java.awt.Color(102, 102, 102));
        solicitudtroqueles.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        solicitudtroqueles.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        solicitudtroqueles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        solicitudtroqueles.setIconTextGap(15);
        solicitudtroqueles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitudtroquelesActionPerformed(evt);
            }
        });
        desktopsolicitudes.add(solicitudtroqueles, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 350, 200, 220));

        solicitudsellos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/solicitudsellos.png"))); // NOI18N
        solicitudsellos.setColorHover(new java.awt.Color(51, 51, 51));
        solicitudsellos.setColorNormal(new java.awt.Color(102, 102, 102));
        solicitudsellos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        solicitudsellos.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        solicitudsellos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        solicitudsellos.setIconTextGap(15);
        solicitudsellos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitudsellosActionPerformed(evt);
            }
        });
        desktopsolicitudes.add(solicitudsellos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 200, 220));

        solicitudarteviejos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/solicitud_arte_viejos.png"))); // NOI18N
        solicitudarteviejos.setColorHover(new java.awt.Color(51, 51, 51));
        solicitudarteviejos.setColorNormal(new java.awt.Color(102, 102, 102));
        solicitudarteviejos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        solicitudarteviejos.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        solicitudarteviejos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        solicitudarteviejos.setIconTextGap(15);
        solicitudarteviejos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitudarteviejosActionPerformed(evt);
            }
        });
        desktopsolicitudes.add(solicitudarteviejos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 200, 220));

        getContentPane().add(desktopsolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 700, 670));

        desktopprocesosdiarios.setBackground(new java.awt.Color(51, 51, 51));
        desktopprocesosdiarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pendientepreprensa.setBackground(new java.awt.Color(51, 51, 51));
        pendientepreprensa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prndiente_preprensa.png"))); // NOI18N
        pendientepreprensa.setColorHover(new java.awt.Color(102, 102, 102));
        pendientepreprensa.setColorNormal(new java.awt.Color(51, 51, 51));
        pendientepreprensa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pendientepreprensa.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        pendientepreprensa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pendientepreprensa.setIconTextGap(15);
        pendientepreprensa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendientepreprensaMouseClicked(evt);
            }
        });
        pendientepreprensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendientepreprensaActionPerformed(evt);
            }
        });
        desktopprocesosdiarios.add(pendientepreprensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 200, 220));

        solicituddearte.setBackground(new java.awt.Color(51, 51, 51));
        solicituddearte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reparacion_sellos.png"))); // NOI18N
        solicituddearte.setColorHover(new java.awt.Color(102, 102, 102));
        solicituddearte.setColorNormal(new java.awt.Color(51, 51, 51));
        solicituddearte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        solicituddearte.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        solicituddearte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        solicituddearte.setIconTextGap(15);
        solicituddearte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicituddearteActionPerformed(evt);
            }
        });
        desktopprocesosdiarios.add(solicituddearte, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 60, 200, 220));

        asignartroquel.setBackground(new java.awt.Color(51, 51, 51));
        asignartroquel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/asugnar_troquel.png"))); // NOI18N
        asignartroquel.setColorHover(new java.awt.Color(102, 102, 102));
        asignartroquel.setColorNormal(new java.awt.Color(51, 51, 51));
        asignartroquel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        asignartroquel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        asignartroquel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        asignartroquel.setIconTextGap(15);
        asignartroquel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignartroquelActionPerformed(evt);
            }
        });
        desktopprocesosdiarios.add(asignartroquel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 200, 220));

        creacionprinmaster.setBackground(new java.awt.Color(51, 51, 51));
        creacionprinmaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/creacion_printmaster.png"))); // NOI18N
        creacionprinmaster.setColorHover(new java.awt.Color(102, 102, 102));
        creacionprinmaster.setColorNormal(new java.awt.Color(51, 51, 51));
        creacionprinmaster.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        creacionprinmaster.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        creacionprinmaster.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        creacionprinmaster.setIconTextGap(15);
        creacionprinmaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creacionprinmasterActionPerformed(evt);
            }
        });
        desktopprocesosdiarios.add(creacionprinmaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 350, 200, 220));

        solicitudes.setBackground(new java.awt.Color(51, 51, 51));
        solicitudes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/solicitudes.png"))); // NOI18N
        solicitudes.setColorHover(new java.awt.Color(102, 102, 102));
        solicitudes.setColorNormal(new java.awt.Color(51, 51, 51));
        solicitudes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        solicitudes.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        solicitudes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        solicitudes.setIconTextGap(15);
        solicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitudesActionPerformed(evt);
            }
        });
        desktopprocesosdiarios.add(solicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 200, 220));

        revision.setBackground(new java.awt.Color(51, 51, 51));
        revision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revision.png"))); // NOI18N
        revision.setColorHover(new java.awt.Color(102, 102, 102));
        revision.setColorNormal(new java.awt.Color(51, 51, 51));
        revision.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        revision.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        revision.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        revision.setIconTextGap(15);
        revision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revisionActionPerformed(evt);
            }
        });
        desktopprocesosdiarios.add(revision, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 200, 220));

        getContentPane().add(desktopprocesosdiarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 700, 670));

        desktopreportes.setBackground(new java.awt.Color(51, 51, 51));
        desktopreportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportetrabajosdepreprensapormes.setBackground(new java.awt.Color(51, 51, 51));
        reportetrabajosdepreprensapormes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trabajospormes.png"))); // NOI18N
        reportetrabajosdepreprensapormes.setColorHover(new java.awt.Color(102, 102, 102));
        reportetrabajosdepreprensapormes.setColorNormal(new java.awt.Color(51, 51, 51));
        reportetrabajosdepreprensapormes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reportetrabajosdepreprensapormes.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        reportetrabajosdepreprensapormes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reportetrabajosdepreprensapormes.setIconTextGap(15);
        reportetrabajosdepreprensapormes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportetrabajosdepreprensapormesActionPerformed(evt);
            }
        });
        desktopreportes.add(reportetrabajosdepreprensapormes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 200, 220));

        reportependientedepreprensa.setBackground(new java.awt.Color(51, 51, 51));
        reportependientedepreprensa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pendientepreprensa.png"))); // NOI18N
        reportependientedepreprensa.setColorHover(new java.awt.Color(102, 102, 102));
        reportependientedepreprensa.setColorNormal(new java.awt.Color(51, 51, 51));
        reportependientedepreprensa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reportependientedepreprensa.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        reportependientedepreprensa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reportependientedepreprensa.setIconTextGap(15);
        reportependientedepreprensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportependientedepreprensaActionPerformed(evt);
            }
        });
        desktopreportes.add(reportependientedepreprensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 60, 200, 220));

        reportependientedereparacion.setBackground(new java.awt.Color(51, 51, 51));
        reportependientedereparacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pendientereparacion.png"))); // NOI18N
        reportependientedereparacion.setColorHover(new java.awt.Color(102, 102, 102));
        reportependientedereparacion.setColorNormal(new java.awt.Color(51, 51, 51));
        reportependientedereparacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reportependientedereparacion.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        reportependientedereparacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reportependientedereparacion.setIconTextGap(15);
        reportependientedereparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportependientedereparacionActionPerformed(evt);
            }
        });
        desktopreportes.add(reportependientedereparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 200, 220));

        reporteprintmaster.setBackground(new java.awt.Color(51, 51, 51));
        reporteprintmaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/printmaster.png"))); // NOI18N
        reporteprintmaster.setColorHover(new java.awt.Color(102, 102, 102));
        reporteprintmaster.setColorNormal(new java.awt.Color(51, 51, 51));
        reporteprintmaster.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reporteprintmaster.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        reporteprintmaster.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reporteprintmaster.setIconTextGap(15);
        reporteprintmaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteprintmasterActionPerformed(evt);
            }
        });
        desktopreportes.add(reporteprintmaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 350, 200, 220));

        reportereimpresiondesolicitudes.setBackground(new java.awt.Color(51, 51, 51));
        reportereimpresiondesolicitudes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reimpresionsolicitudes.png"))); // NOI18N
        reportereimpresiondesolicitudes.setColorHover(new java.awt.Color(102, 102, 102));
        reportereimpresiondesolicitudes.setColorNormal(new java.awt.Color(51, 51, 51));
        reportereimpresiondesolicitudes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reportereimpresiondesolicitudes.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        reportereimpresiondesolicitudes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reportereimpresiondesolicitudes.setIconTextGap(15);
        reportereimpresiondesolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportereimpresiondesolicitudesActionPerformed(evt);
            }
        });
        desktopreportes.add(reportereimpresiondesolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 200, 220));

        getContentPane().add(desktopreportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 700, 670));

        desktopproduccion.setBackground(new java.awt.Color(51, 51, 51));
        desktopproduccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        solicituddemuestra4.setBackground(new java.awt.Color(51, 51, 51));
        solicituddemuestra4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bitacora.png"))); // NOI18N
        solicituddemuestra4.setColorHover(new java.awt.Color(102, 102, 102));
        solicituddemuestra4.setColorNormal(new java.awt.Color(51, 51, 51));
        solicituddemuestra4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        solicituddemuestra4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        solicituddemuestra4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        solicituddemuestra4.setIconTextGap(15);
        solicituddemuestra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicituddemuestra4ActionPerformed(evt);
            }
        });
        desktopproduccion.add(solicituddemuestra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 200, 220));

        getContentPane().add(desktopproduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 700, 670));

        desktoreimpresionsolicitudes.setBackground(new java.awt.Color(102, 102, 102));
        desktoreimpresionsolicitudes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        solicitudmuestra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reimpresionmuestra.png"))); // NOI18N
        solicitudmuestra1.setColorHover(new java.awt.Color(51, 51, 51));
        solicitudmuestra1.setColorNormal(new java.awt.Color(102, 102, 102));
        solicitudmuestra1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        solicitudmuestra1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        solicitudmuestra1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        solicitudmuestra1.setIconTextGap(15);
        solicitudmuestra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                solicitudmuestra1MouseClicked(evt);
            }
        });
        solicitudmuestra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitudmuestra1ActionPerformed(evt);
            }
        });
        desktoreimpresionsolicitudes.add(solicitudmuestra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 200, 220));

        solicitudarte1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reimpresionarte.png"))); // NOI18N
        solicitudarte1.setColorHover(new java.awt.Color(51, 51, 51));
        solicitudarte1.setColorNormal(new java.awt.Color(102, 102, 102));
        solicitudarte1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        solicitudarte1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        solicitudarte1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        solicitudarte1.setIconTextGap(15);
        solicitudarte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitudarte1ActionPerformed(evt);
            }
        });
        desktoreimpresionsolicitudes.add(solicitudarte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 60, 200, 220));

        solicitudtroqueles1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Reimpresióntroquel.png"))); // NOI18N
        solicitudtroqueles1.setColorHover(new java.awt.Color(51, 51, 51));
        solicitudtroqueles1.setColorNormal(new java.awt.Color(102, 102, 102));
        solicitudtroqueles1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        solicitudtroqueles1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        solicitudtroqueles1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        solicitudtroqueles1.setIconTextGap(15);
        solicitudtroqueles1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitudtroqueles1ActionPerformed(evt);
            }
        });
        desktoreimpresionsolicitudes.add(solicitudtroqueles1, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 350, 200, 220));

        solicitudsellos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reimpresionsellos.png"))); // NOI18N
        solicitudsellos1.setColorHover(new java.awt.Color(51, 51, 51));
        solicitudsellos1.setColorNormal(new java.awt.Color(102, 102, 102));
        solicitudsellos1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        solicitudsellos1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        solicitudsellos1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        solicitudsellos1.setIconTextGap(15);
        solicitudsellos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitudsellos1ActionPerformed(evt);
            }
        });
        desktoreimpresionsolicitudes.add(solicitudsellos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 200, 220));

        getContentPane().add(desktoreimpresionsolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 700, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void produccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produccionMouseClicked
        
    }//GEN-LAST:event_produccionMouseClicked

    private void reportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportesMouseClicked
        
    }//GEN-LAST:event_reportesMouseClicked

    private void procesosdiariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_procesosdiariosMouseClicked

    }//GEN-LAST:event_procesosdiariosMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton5MouseClicked

    private void pendientepreprensaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendientepreprensaMouseClicked
       // PendientePreprensa abrir = new PendientePreprensa();
       // abrir.setVisible(true);

    }//GEN-LAST:event_pendientepreprensaMouseClicked

    private void procesosdiariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesosdiariosActionPerformed
        // TODO add your handling code here:
        desktopprocesosdiarios.setVisible(true);
        desktopreportes.setVisible(false);
        desktopproduccion.setVisible(false);
        desktopsolicitudes.setVisible(false);
        desktoreimpresionsolicitudes.setVisible(false);
        desktoplogo.setVisible(false);
    }//GEN-LAST:event_procesosdiariosActionPerformed

    private void reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesActionPerformed
        desktopprocesosdiarios.setVisible(false);
        desktopreportes.setVisible(true);
        desktopproduccion.setVisible(false);
        desktopsolicitudes.setVisible(false);
        desktoreimpresionsolicitudes.setVisible(false);
        desktoplogo.setVisible(false);
    }//GEN-LAST:event_reportesActionPerformed

    private void produccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produccionActionPerformed
        desktopprocesosdiarios.setVisible(false);
        desktopreportes.setVisible(false);
        desktopproduccion.setVisible(true);
        desktopsolicitudes.setVisible(false);
        desktoreimpresionsolicitudes.setVisible(false);
        desktoplogo.setVisible(false);
    }//GEN-LAST:event_produccionActionPerformed

    private void solicitudmuestraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solicitudmuestraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_solicitudmuestraMouseClicked

    private void solicitudmuestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitudmuestraActionPerformed
        SolicitudMuestra Sm = new SolicitudMuestra();
        Sm.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_solicitudmuestraActionPerformed

    private void pendientepreprensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendientepreprensaActionPerformed
        PendientePreprensa PendientePreprensa = new PendientePreprensa();
        PendientePreprensa.setVisible(true);
        
        this.setVisible(false);
             
    }//GEN-LAST:event_pendientepreprensaActionPerformed

    private void solicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitudesActionPerformed
        desktopprocesosdiarios.setVisible(false);
        desktopreportes.setVisible(false);
        desktopproduccion.setVisible(false);
        desktopsolicitudes.setVisible(true);
        desktoreimpresionsolicitudes.setVisible(false);
        desktoplogo.setVisible(false);
    }//GEN-LAST:event_solicitudesActionPerformed

    private void solicitudarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitudarteActionPerformed
        // TODO add your handling code here:
        SolicitudArte SolicitudArte = new SolicitudArte();
        SolicitudArte.setVisible(true);
        
        this.setVisible(false);

    }//GEN-LAST:event_solicitudarteActionPerformed

    private void solicitudsellosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitudsellosActionPerformed
               
        SolicitudSellos SolicitudSellos = new SolicitudSellos();
        SolicitudSellos.setVisible(true);
        
        this.setVisible(true);
        
        Interfaz i = new Interfaz();
        i.setVisible(true);
        
        
    }//GEN-LAST:event_solicitudsellosActionPerformed

    private void creacionprinmasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creacionprinmasterActionPerformed
        // TODO add your handling code here:
        Printmaster Printmaster = new Printmaster();
        Printmaster.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_creacionprinmasterActionPerformed

    private void asignartroquelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignartroquelActionPerformed
        // TODO add your handling code here:
        AsignarTroquel AsignarTroquel = new AsignarTroquel();
        AsignarTroquel.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_asignartroquelActionPerformed

    private void solicitudarteviejosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitudarteviejosActionPerformed
        // TODO add your handling code here:
        SolicitudArteviejo SolicitudArteviejo = new SolicitudArteviejo();
        SolicitudArteviejo.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_solicitudarteviejosActionPerformed

    private void reporteprintmasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteprintmasterActionPerformed
        // TODO add your handling code here:
        Rprintmaster Rprintmaster = new Rprintmaster();
        Rprintmaster.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_reporteprintmasterActionPerformed

    private void solicitudtroquelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitudtroquelesActionPerformed
        // TODO add your handling code here:
        SolicitudTroqueles SolicitudTroqueles = new SolicitudTroqueles();
        SolicitudTroqueles.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_solicitudtroquelesActionPerformed

    private void revisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revisionActionPerformed
        // TODO add your handling code here:
        RevisionArtesSellossTroqueles RevisionArtesSellossTroqueles = new RevisionArtesSellossTroqueles();
        RevisionArtesSellossTroqueles.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_revisionActionPerformed

    private void solicituddemuestra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicituddemuestra4ActionPerformed
        // TODO add your handling code here:
         Produccion Produccion = new Produccion();
        Produccion.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_solicituddemuestra4ActionPerformed

    private void solicituddearteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicituddearteActionPerformed
        // TODO add your handling code here:
        PendienteReparaciondeSellos PendienteReparaciondeSellos = new PendienteReparaciondeSellos();
        PendienteReparaciondeSellos.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_solicituddearteActionPerformed

    private void reportependientedepreprensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportependientedepreprensaActionPerformed
        // TODO add your handling code here:
        ReporteSolicitudesPendiente ReporteSolicitudesPendiente = new ReporteSolicitudesPendiente();
        ReporteSolicitudesPendiente.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_reportependientedepreprensaActionPerformed

    private void reportependientedereparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportependientedereparacionActionPerformed
        // TODO add your handling code here:
        PendienteReparaciondeSellos PendienteReparaciondeSellos = new PendienteReparaciondeSellos();
        PendienteReparaciondeSellos.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_reportependientedereparacionActionPerformed

    private void reportetrabajosdepreprensapormesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportetrabajosdepreprensapormesActionPerformed
        // TODO add your handling code here:
        TrabajosRealizadosporMes TrabajosRealizadosporMes = new TrabajosRealizadosporMes();
        TrabajosRealizadosporMes.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_reportetrabajosdepreprensapormesActionPerformed

    private void solicitudmuestra1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solicitudmuestra1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_solicitudmuestra1MouseClicked

    private void solicitudmuestra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitudmuestra1ActionPerformed
        // TODO add your handling code here:
         ReimpresionMuestra ReimpresionMuestra = new ReimpresionMuestra();
        ReimpresionMuestra.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_solicitudmuestra1ActionPerformed

    private void solicitudarte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitudarte1ActionPerformed
        // TODO add your handling code here:
        ReimpresionArtes ReimpresionArtes = new ReimpresionArtes();
        ReimpresionArtes.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_solicitudarte1ActionPerformed

    private void solicitudtroqueles1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitudtroqueles1ActionPerformed
        // TODO add your handling code here:
        ReimpresionTroqueles ReimpresionTroqueles = new ReimpresionTroqueles();
        ReimpresionTroqueles.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_solicitudtroqueles1ActionPerformed

    private void solicitudsellos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitudsellos1ActionPerformed
        // TODO add your handling code here:
        ReimpresionSellos ReimpresionSellos = new ReimpresionSellos();
        ReimpresionSellos.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_solicitudsellos1ActionPerformed

    private void reportereimpresiondesolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportereimpresiondesolicitudesActionPerformed
        // TODO add your handling code here:
        desktopprocesosdiarios.setVisible(false);
        desktopreportes.setVisible(false);
        desktopproduccion.setVisible(false);
        desktopsolicitudes.setVisible(false);
        desktoreimpresionsolicitudes.setVisible(true);
        desktoplogo.setVisible(false);
    }//GEN-LAST:event_reportereimpresiondesolicitudesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro asignartroquel;
    private rsbuttom.RSButtonMetro creacionprinmaster;
    private javax.swing.JPanel desktoplogo;
    private javax.swing.JPanel desktopprocesosdiarios;
    private javax.swing.JPanel desktopproduccion;
    private javax.swing.JPanel desktopreportes;
    private javax.swing.JPanel desktopsolicitudes;
    private javax.swing.JPanel desktoreimpresionsolicitudes;
    private javax.swing.JButton jButton5;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel menu;
    private rsbuttom.RSButtonMetro pendientepreprensa;
    private rsbuttom.RSButtonMetro procesosdiarios;
    private rsbuttom.RSButtonMetro produccion;
    private rsbuttom.RSButtonMetro reportependientedepreprensa;
    private rsbuttom.RSButtonMetro reportependientedereparacion;
    private rsbuttom.RSButtonMetro reporteprintmaster;
    private rsbuttom.RSButtonMetro reportereimpresiondesolicitudes;
    private rsbuttom.RSButtonMetro reportes;
    private rsbuttom.RSButtonMetro reportetrabajosdepreprensapormes;
    private rsbuttom.RSButtonMetro revision;
    private rsbuttom.RSButtonMetro solicitudarte;
    private rsbuttom.RSButtonMetro solicitudarte1;
    private rsbuttom.RSButtonMetro solicitudarteviejos;
    private rsbuttom.RSButtonMetro solicituddearte;
    private rsbuttom.RSButtonMetro solicituddemuestra4;
    private rsbuttom.RSButtonMetro solicitudes;
    private rsbuttom.RSButtonMetro solicitudmuestra;
    private rsbuttom.RSButtonMetro solicitudmuestra1;
    private rsbuttom.RSButtonMetro solicitudsellos;
    private rsbuttom.RSButtonMetro solicitudsellos1;
    private rsbuttom.RSButtonMetro solicitudtroqueles;
    private rsbuttom.RSButtonMetro solicitudtroqueles1;
    // End of variables declaration//GEN-END:variables
}
