/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author jpaula
 */
public class PrintmasterReporte extends javax.swing.JFrame {

    /**
     * Creates new form Rpm
     */
    public PrintmasterReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportearte = new javax.swing.JPanel();
        dimenciones = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        largototalpulgada = new javax.swing.JTextField();
        anchototalpulgada = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        gapsuperior = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        gapinferior = new javax.swing.JTextField();
        gapsuperiormm = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        gapinferior1 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        largo = new javax.swing.JTextField();
        alto = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        largomilimetro = new javax.swing.JTextField();
        anchomilimetros = new javax.swing.JTextField();
        altomilimetros = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        ancho1 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        panelsuperior = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        panelsuperior1 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        panelsuperior2 = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        largo1 = new javax.swing.JTextField();
        ancho2 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        largomilimetro1 = new javax.swing.JTextField();
        anchomilimetros1 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        caracteristicas = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        tipocaja = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        categoriacaja = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        test = new javax.swing.JTextField();
        flauta = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        cierre = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        papelexterno = new javax.swing.JTextField();
        papelinterno = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        colaterminado = new javax.swing.JTextField();
        cera = new javax.swing.JTextField();
        MT = new javax.swing.JTextField();
        resina = new javax.swing.JTextField();
        colacorrugadora = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        componenteancho = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        componentelargo = new javax.swing.JTextField();
        componenteancho1 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        color6gcmi = new javax.swing.JTextField();
        color1 = new javax.swing.JTextField();
        color2 = new javax.swing.JTextField();
        color6 = new javax.swing.JTextField();
        color3 = new javax.swing.JTextField();
        color4 = new javax.swing.JTextField();
        color5 = new javax.swing.JTextField();
        color1gcmi = new javax.swing.JTextField();
        color2gcmi = new javax.swing.JTextField();
        color3gcmi = new javax.swing.JTextField();
        color4gcmi = new javax.swing.JTextField();
        color5gcmi = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        sellotest = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        personalizado = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        unidadxpaquete = new javax.swing.JTextField();
        plstificado = new javax.swing.JTextField();
        basexaltura = new javax.swing.JTextField();
        cajaxpaleta = new javax.swing.JTextField();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        largopaquete = new javax.swing.JTextField();
        anchopaquete = new javax.swing.JTextField();
        altopaquete = new javax.swing.JTextField();
        jPanel30 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        numerotroquel = new javax.swing.JTextField();
        enfundado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        diseñadopor = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        imagenprintmaster = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        grupo = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        codigocliente = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        codigoproducto = new javax.swing.JTextField();
        nombrecliente = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        componente = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        LOGO1 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        idmuestra = new javax.swing.JTextField();
        idarte = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        reportearte.setBackground(new java.awt.Color(255, 255, 255));
        reportearte.setToolTipText("");
        reportearte.setAutoscrolls(true);
        reportearte.setInheritsPopupMenu(true);
        reportearte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dimenciones.setBackground(new java.awt.Color(255, 255, 255));
        dimenciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dimenciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(204, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Largo de Lámina :");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Ancho de Lámina :");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, -1));

        largototalpulgada.setEditable(false);
        largototalpulgada.setBackground(new java.awt.Color(204, 255, 255));
        largototalpulgada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        largototalpulgada.setText("98.5000");
        largototalpulgada.setBorder(null);
        jPanel9.add(largototalpulgada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 3, 70, 15));

        anchototalpulgada.setEditable(false);
        anchototalpulgada.setBackground(new java.awt.Color(204, 255, 255));
        anchototalpulgada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        anchototalpulgada.setText("66.0000");
        anchototalpulgada.setBorder(null);
        jPanel9.add(anchototalpulgada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 28, 70, 15));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("pulg.");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("pulg.");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 24, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 255, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setText("1,958");
        jTextField1.setBorder(null);
        jPanel9.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 5, 50, 15));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 255, 255));
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setText("1,200");
        jTextField2.setBorder(null);
        jPanel9.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 28, 50, 15));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("mm.");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("mm.");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 24, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/montage-01.jpg"))); // NOI18N
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 60, 50));

        dimenciones.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 800, 50));

        jPanel13.setBackground(new java.awt.Color(102, 204, 0));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Gap Sup :");
        jPanel13.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setText("Gap Inf :");
        jPanel13.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 9, -1, -1));

        gapsuperior.setBackground(new java.awt.Color(102, 204, 0));
        gapsuperior.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gapsuperior.setText("1.0000");
        gapsuperior.setBorder(null);
        jPanel13.add(gapsuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 13, -1, 15));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setText("pulg.");
        jPanel13.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 9, -1, -1));

        gapinferior.setBackground(new java.awt.Color(102, 204, 0));
        gapinferior.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gapinferior.setText("1.0000");
        gapinferior.setBorder(null);
        jPanel13.add(gapinferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 13, -1, 16));

        gapsuperiormm.setBackground(new java.awt.Color(102, 204, 0));
        gapsuperiormm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gapsuperiormm.setText("1.0000");
        gapsuperiormm.setBorder(null);
        jPanel13.add(gapsuperiormm, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 13, -1, 16));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setText("mm.");
        jPanel13.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 9, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setText("pulg.");
        jPanel13.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 9, -1, -1));

        gapinferior1.setBackground(new java.awt.Color(102, 204, 0));
        gapinferior1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gapinferior1.setText("1.0000");
        gapinferior1.setBorder(null);
        jPanel13.add(gapinferior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 13, -1, 16));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setText("mm.");
        jPanel13.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 9, -1, -1));

        jLabel63.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel63.setText("Cola Terminado:");
        jPanel13.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, -1, -1));

        dimenciones.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 169, 800, 40));

        jPanel10.setBackground(new java.awt.Color(51, 51, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Tolerancia");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 5, -1, -1));

        dimenciones.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 141, 30));

        jPanel16.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        dimenciones.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 104, 140, 3));

        jPanel11.setBackground(new java.awt.Color(204, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("3ds", 0, 13)); // NOI18N
        jLabel49.setText("+/- 1/8 pulg. (3 mms)");
        jPanel11.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 4, -1, 17));

        dimenciones.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 141, 24));

        jPanel12.setBackground(new java.awt.Color(204, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("3ds", 1, 18)); // NOI18N
        jLabel20.setText("Largo :");
        jPanel12.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel23.setFont(new java.awt.Font("3ds", 1, 18)); // NOI18N
        jLabel23.setText("Ancho :");
        jPanel12.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, 15));

        jLabel24.setFont(new java.awt.Font("3ds", 1, 18)); // NOI18N
        jLabel24.setText("Alto :");
        jPanel12.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, -1, 15));

        largo.setEditable(false);
        largo.setBackground(new java.awt.Color(204, 255, 255));
        largo.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        largo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        largo.setText("18.3750");
        largo.setBorder(null);
        jPanel12.add(largo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 7, 80, 15));

        alto.setEditable(false);
        alto.setBackground(new java.awt.Color(204, 255, 255));
        alto.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        alto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alto.setText("10.2500");
        alto.setBorder(null);
        jPanel12.add(alto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 66, 80, 15));

        jLabel28.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel28.setText("mm");
        jPanel12.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 5, -1, 17));

        jLabel29.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel29.setText("mm");
        jPanel12.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 30, -1, -1));

        jLabel30.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel30.setText("mm");
        jPanel12.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 60, -1, -1));

        largomilimetro.setBackground(new java.awt.Color(204, 255, 255));
        largomilimetro.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        largomilimetro.setText("1,958");
        largomilimetro.setBorder(null);
        largomilimetro.setSelectionEnd(4);
        jPanel12.add(largomilimetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 7, 60, 15));

        anchomilimetros.setBackground(new java.awt.Color(204, 255, 255));
        anchomilimetros.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        anchomilimetros.setText("1,958");
        anchomilimetros.setBorder(null);
        anchomilimetros.setSelectionEnd(4);
        jPanel12.add(anchomilimetros, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 35, 60, 15));

        altomilimetros.setBackground(new java.awt.Color(204, 255, 255));
        altomilimetros.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        altomilimetros.setText("1,958");
        altomilimetros.setBorder(null);
        altomilimetros.setSelectionEnd(4);
        jPanel12.add(altomilimetros, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 66, 50, 15));

        jLabel31.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel31.setText("mm");
        jPanel12.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        jLabel32.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel32.setText("mm");
        jPanel12.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jLabel34.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel34.setText("mm");
        jPanel12.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jPanel14.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 330, 3));

        jPanel15.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 330, 3));

        ancho1.setEditable(false);
        ancho1.setBackground(new java.awt.Color(204, 255, 255));
        ancho1.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        ancho1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ancho1.setText("10.2500");
        ancho1.setBorder(null);
        jPanel12.add(ancho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 35, 80, 15));

        jLabel43.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel43.setText("pulg");
        jPanel12.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 5, -1, 17));

        jLabel44.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel44.setText("pulg");
        jPanel12.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel45.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel45.setText("pulg");
        jPanel12.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        dimenciones.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 79, 330, 90));

        jLabel22.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel22.setText("Paneles Lámina : ");
        dimenciones.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 53, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("MEDIDAS TOTALES");
        dimenciones.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        panelsuperior.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        panelsuperior.setText("197");
        panelsuperior.setBorder(null);
        dimenciones.add(panelsuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 40, 12));

        jLabel41.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel41.setText("mm");
        dimenciones.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, 12));

        jLabel42.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel42.setText("/");
        dimenciones.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 60, -1, 12));

        jLabel46.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel46.setText("mm");
        dimenciones.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, 12));

        panelsuperior1.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        panelsuperior1.setText("197");
        panelsuperior1.setBorder(null);
        dimenciones.add(panelsuperior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 40, 12));

        jLabel47.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel47.setText("/");
        dimenciones.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, 12));

        jLabel48.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel48.setText("mm");
        dimenciones.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, 12));

        panelsuperior2.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        panelsuperior2.setText("197");
        panelsuperior2.setBorder(null);
        dimenciones.add(panelsuperior2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 40, 12));

        jPanel17.setBackground(new java.awt.Color(204, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 330, 3));

        jLabel50.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel50.setText("Largo :");
        jPanel17.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel51.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel51.setText("Ancho :");
        jPanel17.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, 15));

        largo1.setEditable(false);
        largo1.setBackground(new java.awt.Color(204, 255, 255));
        largo1.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        largo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        largo1.setText("18.3750");
        largo1.setBorder(null);
        jPanel17.add(largo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 7, 80, 15));

        ancho2.setEditable(false);
        ancho2.setBackground(new java.awt.Color(204, 255, 255));
        ancho2.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        ancho2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ancho2.setText("10.2500");
        ancho2.setBorder(null);
        jPanel17.add(ancho2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 35, 80, 15));

        jLabel52.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel52.setText("pulg");
        jPanel17.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 5, -1, 17));

        jLabel53.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel53.setText("pulg");
        jPanel17.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        largomilimetro1.setBackground(new java.awt.Color(204, 255, 255));
        largomilimetro1.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        largomilimetro1.setText("1,958");
        largomilimetro1.setBorder(null);
        largomilimetro1.setSelectionEnd(4);
        jPanel17.add(largomilimetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 7, 60, 15));

        anchomilimetros1.setBackground(new java.awt.Color(204, 255, 255));
        anchomilimetros1.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        anchomilimetros1.setText("1,958");
        anchomilimetros1.setBorder(null);
        anchomilimetros1.setSelectionEnd(4);
        anchomilimetros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anchomilimetros1ActionPerformed(evt);
            }
        });
        jPanel17.add(anchomilimetros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 35, 60, 15));

        jLabel54.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel54.setText("mm");
        jPanel17.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 5, -1, 17));

        jLabel55.setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N
        jLabel55.setText("mm");
        jPanel17.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 30, -1, -1));

        dimenciones.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 79, 330, 55));

        caracteristicas.setBackground(new java.awt.Color(255, 255, 255));
        caracteristicas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        caracteristicas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipocaja.setBackground(new java.awt.Color(204, 255, 255));
        tipocaja.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tipocaja.setText("TROQUELADA");
        tipocaja.setBorder(null);
        jPanel7.add(tipocaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 310, -1));

        jLabel56.setText("Categoria :");
        jPanel7.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 27, -1, -1));

        categoriacaja.setBackground(new java.awt.Color(204, 255, 255));
        categoriacaja.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        categoriacaja.setText("AGR");
        categoriacaja.setBorder(null);
        jPanel7.add(categoriacaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 26, 90, -1));

        jLabel58.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel58.setText("Test:");
        jPanel7.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 26, -1, -1));

        test.setBackground(new java.awt.Color(204, 255, 255));
        test.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        test.setText("E82");
        test.setBorder(null);
        jPanel7.add(test, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 28, 30, 15));

        flauta.setBackground(new java.awt.Color(204, 255, 255));
        flauta.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        flauta.setText("BC");
        flauta.setBorder(null);
        jPanel7.add(flauta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 28, -1, -1));

        caracteristicas.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 318, 50));

        jLabel60.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel60.setText("Papel Ext:");
        caracteristicas.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel61.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel61.setText("Tratamiento Esp:");
        caracteristicas.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, -1, -1));

        jLabel62.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel62.setText("Cola Corrugadora:");
        caracteristicas.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel64.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel64.setText("Cola Terminado:");
        caracteristicas.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, -1, -1));

        jPanel18.setBackground(new java.awt.Color(102, 153, 0));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel65.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel65.setText("Cierre:");
        jPanel18.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 9, -1, -1));

        caracteristicas.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 169, 140, 40));

        jPanel20.setBackground(new java.awt.Color(102, 204, 0));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cierre.setBackground(new java.awt.Color(102, 204, 0));
        cierre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cierre.setText("NO LLEVA");
        cierre.setBorder(null);
        jPanel20.add(cierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 20));

        caracteristicas.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 169, 179, 40));

        jPanel23.setBackground(new java.awt.Color(204, 255, 255));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        papelexterno.setBackground(new java.awt.Color(204, 255, 255));
        papelexterno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        papelexterno.setText("BLANCO");
        papelexterno.setBorder(null);
        jPanel23.add(papelexterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 0, -1, -1));

        papelinterno.setBackground(new java.awt.Color(204, 255, 255));
        papelinterno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        papelinterno.setText("KRF");
        papelinterno.setBorder(null);
        jPanel23.add(papelinterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel69.setBackground(new java.awt.Color(255, 255, 255));
        jLabel69.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel69.setText("Int:");
        jPanel23.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 0, 30, 15));

        jTextField11.setBorder(null);
        jPanel23.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 0, 40, 20));

        jTextField12.setBorder(null);
        jPanel23.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 158, 4));

        colaterminado.setBackground(new java.awt.Color(204, 255, 255));
        colaterminado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        colaterminado.setText("NO LLEVA");
        colaterminado.setBorder(null);
        jPanel23.add(colaterminado, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 78, -1, -1));

        cera.setBackground(new java.awt.Color(204, 255, 255));
        cera.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cera.setText("CERA");
        cera.setBorder(null);
        jPanel23.add(cera, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        MT.setBackground(new java.awt.Color(204, 255, 255));
        MT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        MT.setText("MT");
        MT.setBorder(null);
        jPanel23.add(MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        resina.setBackground(new java.awt.Color(204, 255, 255));
        resina.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        resina.setText("RESINA");
        resina.setBorder(null);
        jPanel23.add(resina, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 30, -1, -1));

        colacorrugadora.setBackground(new java.awt.Color(204, 255, 255));
        colacorrugadora.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        colacorrugadora.setText("NORMAL");
        colacorrugadora.setBorder(null);
        jPanel23.add(colacorrugadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 53, -1, -1));

        caracteristicas.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 58, 158, 100));

        dimenciones.add(caracteristicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 0, 320, 210));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setText("Componente(s) por hojas");
        jPanel21.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, -1, -1, -1));

        componenteancho.setText("100");
        componenteancho.setBorder(null);
        jPanel21.add(componenteancho, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 18, 20, 15));

        jLabel66.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel66.setText("Total:");
        jPanel21.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 17, -1, -1));

        jLabel67.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel67.setText("Largo:");
        jPanel21.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 17, -1, -1));

        jLabel68.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel68.setText("Ancho:");
        jPanel21.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 17, -1, -1));

        componentelargo.setText("100");
        componentelargo.setBorder(null);
        jPanel21.add(componentelargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 18, 20, 15));

        componenteancho1.setText("100");
        componenteancho1.setBorder(null);
        jPanel21.add(componenteancho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 18, 20, 15));

        dimenciones.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 134, 471, 34));

        jTextField7.setBackground(new java.awt.Color(51, 51, 255));
        jTextField7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setText("  Impresión:");
        jTextField7.setBorder(null);
        dimenciones.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1119, 3, 93, 25));

        jPanel22.setBackground(new java.awt.Color(102, 153, 255));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel70.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("1re Color");
        jPanel22.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel71.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("2do Color");
        jPanel22.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel72.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("3er Color");
        jPanel22.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel73.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("4to Color");
        jPanel22.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, -1, -1));

        jLabel74.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("6to Color");
        jPanel22.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 102, -1, -1));

        jLabel75.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("5to Color");
        jPanel22.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, -1, -1));

        dimenciones.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 32, 93, 125));

        color6gcmi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        color6gcmi.setText("NEGRO 33");
        color6gcmi.setBorder(null);
        dimenciones.add(color6gcmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 134, 100, -1));

        color1.setBackground(new java.awt.Color(0, 255, 255));
        color1.setBorder(null);
        dimenciones.add(color1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 30, 30, -1));

        color2.setBackground(new java.awt.Color(255, 0, 102));
        color2.setBorder(null);
        dimenciones.add(color2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 51, 30, -1));

        color6.setBackground(new java.awt.Color(51, 0, 153));
        color6.setBorder(null);
        dimenciones.add(color6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 136, 30, -1));

        color3.setBackground(new java.awt.Color(255, 255, 0));
        color3.setBorder(null);
        dimenciones.add(color3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 72, 30, -1));

        color4.setBackground(new java.awt.Color(0, 0, 0));
        color4.setBorder(null);
        dimenciones.add(color4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 95, 30, -1));

        color5.setBackground(new java.awt.Color(51, 255, 51));
        color5.setBorder(null);
        dimenciones.add(color5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 115, 30, -1));

        color1gcmi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        color1gcmi.setText("AZUL 33");
        color1gcmi.setBorder(null);
        dimenciones.add(color1gcmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 30, 80, -1));

        color2gcmi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        color2gcmi.setText("ROJO 33");
        color2gcmi.setBorder(null);
        dimenciones.add(color2gcmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 52, 80, -1));

        color3gcmi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        color3gcmi.setText("AMARILLO 33");
        color3gcmi.setBorder(null);
        dimenciones.add(color3gcmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 73, 100, -1));

        color4gcmi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        color4gcmi.setText("NEGRO 33");
        color4gcmi.setBorder(null);
        dimenciones.add(color4gcmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 92, 100, -1));

        color5gcmi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        color5gcmi.setText("NEGRO 33");
        color5gcmi.setBorder(null);
        dimenciones.add(color5gcmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 113, 100, -1));

        jPanel24.setBackground(new java.awt.Color(102, 153, 0));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel76.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel76.setText("Sello Test");
        jPanel24.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        dimenciones.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 169, 93, 40));

        sellotest.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sellotest.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellotest.setText("SI");
        dimenciones.add(sellotest, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 178, 29, 25));

        jPanel25.setBackground(new java.awt.Color(102, 153, 0));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel77.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel77.setText("Personalizado");
        jPanel25.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        dimenciones.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1255, 169, 120, 40));

        personalizado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        personalizado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        personalizado.setText("NO");
        dimenciones.add(personalizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 178, 30, 25));

        jPanel26.setBackground(new java.awt.Color(204, 255, 255));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel78.setText("Uds X Paguete:");
        jPanel26.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, -1, -1));

        jLabel79.setText("Base X Altura:");
        jPanel26.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 25, -1, -1));

        jLabel80.setText("Caja X Paleta:");
        jPanel26.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 48, -1, -1));

        jLabel81.setText("Plastificado");
        jPanel26.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 70, -1, -1));

        jLabel85.setText("Enfundado");
        jPanel26.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 92, -1, -1));

        dimenciones.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 10, 93, 110));

        jPanel27.setBackground(new java.awt.Color(204, 255, 255));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel82.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel82.setText("DIMENSIONES PAQUETE");
        jPanel27.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 5, -1, -1));

        dimenciones.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1378, 125, 138, 25));

        unidadxpaquete.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        unidadxpaquete.setText("25");
        unidadxpaquete.setBorder(null);
        dimenciones.add(unidadxpaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1479, 15, 30, -1));

        plstificado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        plstificado.setText("NO");
        plstificado.setBorder(null);
        dimenciones.add(plstificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1479, 81, 30, -1));

        basexaltura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        basexaltura.setText("6 x 7");
        basexaltura.setBorder(null);
        dimenciones.add(basexaltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(1479, 38, 30, -1));

        cajaxpaleta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaxpaleta.setText("1050");
        cajaxpaleta.setBorder(null);
        dimenciones.add(cajaxpaleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1479, 60, 30, -1));

        jPanel28.setBackground(new java.awt.Color(102, 153, 0));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel29.setBackground(new java.awt.Color(102, 204, 0));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel84.setText("Largo:");
        jPanel29.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 2, -1, -1));

        jPanel28.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 169, 50, 40));

        largopaquete.setBackground(new java.awt.Color(102, 153, 0));
        largopaquete.setText("567");
        largopaquete.setBorder(null);
        jPanel28.add(largopaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1, -1, 15));

        anchopaquete.setBackground(new java.awt.Color(102, 153, 0));
        anchopaquete.setText("609");
        anchopaquete.setBorder(null);
        jPanel28.add(anchopaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 15));

        altopaquete.setBackground(new java.awt.Color(102, 153, 0));
        altopaquete.setText("235");
        altopaquete.setBorder(null);
        jPanel28.add(altopaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, -1, 15));

        dimenciones.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1465, 154, 52, 55));

        jPanel30.setBackground(new java.awt.Color(102, 204, 0));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel87.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel87.setText("Largo:");
        jPanel30.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 1, -1, -1));

        jPanel31.setBackground(new java.awt.Color(102, 204, 0));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel88.setText("Largo:");
        jPanel31.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 2, -1, -1));

        jPanel30.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 169, 50, 40));

        jLabel89.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel89.setText("Alto:");
        jPanel30.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 36, -1, -1));

        jLabel90.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel90.setText("Ancho:");
        jPanel30.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 19, -1, -1));

        dimenciones.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1415, 154, 50, 55));

        jPanel32.setBackground(new java.awt.Color(51, 51, 255));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel83.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("Troquel:");
        jPanel32.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 10, -1, -1));

        numerotroquel.setBackground(new java.awt.Color(51, 51, 255));
        numerotroquel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        numerotroquel.setForeground(new java.awt.Color(255, 255, 255));
        numerotroquel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numerotroquel.setText("W-12541");
        numerotroquel.setBorder(null);
        jPanel32.add(numerotroquel, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 11, 68, -1));

        dimenciones.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 141, 40));

        enfundado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enfundado.setText("NO");
        enfundado.setBorder(null);
        dimenciones.add(enfundado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1479, 100, 30, -1));

        reportearte.add(dimenciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 800, 1518, 210));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("DIMENSIONES");
        reportearte.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 780, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("CARACTERÍSTICAS");
        reportearte.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 780, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("PALETIZADO");
        reportearte.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 780, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("LOS TONOS DE LOS COLORES EN EL DISEÑO NO NECESARIAMENTE CORRESPONDEN A LOS DE LA IMPRESION FINAL");
        reportearte.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 172, 690, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("DISEÑADO POR:");
        reportearte.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1335, 173, -1, 15));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel33.setText("SECUENCIA DE COLORES");
        reportearte.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 780, -1, -1));

        jLabel86.setText("Aprovado Cliente");
        reportearte.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 1015, -1, -1));

        jLabel91.setText("Aprovado Ventas");
        reportearte.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 1015, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("FORM. ARTE.");
        reportearte.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 23, 80, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("FORM. MUESTRA:");
        reportearte.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 23, -1, -1));

        diseñadopor.setEditable(false);
        diseñadopor.setBackground(new java.awt.Color(255, 255, 255));
        diseñadopor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        diseñadopor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        diseñadopor.setText("RFERNANDEZ");
        diseñadopor.setBorder(null);
        reportearte.add(diseñadopor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 173, 100, 15));

        jTextField8.setBackground(new java.awt.Color(0, 0, 0));
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reportearte.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 1062, 270, 1));

        jTextField9.setBackground(new java.awt.Color(0, 0, 0));
        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reportearte.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1115, 1062, 270, 1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imagenprintmaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print-master-Template.jpg"))); // NOI18N
        imagenprintmaster.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenprintmaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(imagenprintmaster, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        reportearte.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 1520, 590));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Cóodigo :");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Cliente :");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Producto :");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 53, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Fecha Creacióon :");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, -1, -1));

        grupo.setEditable(false);
        grupo.setBackground(new java.awt.Color(255, 255, 255));
        grupo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        grupo.setText("08");
        grupo.setBorder(null);
        jPanel5.add(grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 13, 30, 15));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField3.setText("-");
        jTextField3.setBorder(null);
        jPanel5.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 13, 10, 15));

        codigocliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        codigocliente.setText("000718");
        codigocliente.setBorder(null);
        jPanel5.add(codigocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 13, 70, 15));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField6.setText("-");
        jTextField6.setBorder(null);
        jPanel5.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 13, 10, 15));

        codigoproducto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        codigoproducto.setText("2009");
        codigoproducto.setBorder(null);
        jPanel5.add(codigoproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 13, 50, 15));

        nombrecliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombrecliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nombrecliente.setText("EXPORTADORA BASURA");
        nombrecliente.setBorder(null);
        jPanel5.add(nombrecliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 35, 440, 16));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField5.setText("VEGETALES AMRGOS");
        jTextField5.setBorder(null);
        jPanel5.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 56, 440, 16));

        fecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fecha.setText("01-07-2019");
        fecha.setBorder(null);
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });
        jPanel5.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 78, 120, 16));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("-");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 13, 10, 15));

        componente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        componente.setText("0");
        jPanel5.add(componente, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 13, 20, 15));

        reportearte.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 550, 110));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGO CARTONES PM.png"))); // NOI18N
        LOGO1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(LOGO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 3, 290, 90));

        reportearte.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 410, 110));

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        reportearte.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 60, 560, 110));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PRIN MASTER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 3, -1, -1));

        jLabel59.setBackground(new java.awt.Color(255, 255, 255));
        jLabel59.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("INSTRUCIONES ESPECIALES:");
        jPanel2.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 190, -1));

        reportearte.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 1520, 20));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idmuestra.setEditable(false);
        idmuestra.setBackground(new java.awt.Color(204, 255, 255));
        idmuestra.setText("000000");
        idmuestra.setBorder(null);
        jPanel1.add(idmuestra, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 4, 50, 15));

        idarte.setEditable(false);
        idarte.setBackground(new java.awt.Color(204, 255, 255));
        idarte.setText("51000");
        idarte.setBorder(null);
        jPanel1.add(idarte, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 4, 50, 15));

        jLabel57.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel57.setText("CÓDIGO ANTERIOR:");
        jPanel1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 3, -1, -1));

        jTextField4.setBackground(new java.awt.Color(204, 255, 255));
        jTextField4.setText("999997-0465");
        jTextField4.setBorder(null);
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 2, 80, 15));

        reportearte.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1520, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1570, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(reportearte, javax.swing.GroupLayout.PREFERRED_SIZE, 1570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(reportearte, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anchomilimetros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anchomilimetros1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anchomilimetros1ActionPerformed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintmasterReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintmasterReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintmasterReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintmasterReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintmasterReporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO1;
    private javax.swing.JTextField MT;
    private javax.swing.JTextField alto;
    private javax.swing.JTextField altomilimetros;
    private javax.swing.JTextField altopaquete;
    private javax.swing.JTextField ancho1;
    private javax.swing.JTextField ancho2;
    private javax.swing.JTextField anchomilimetros;
    private javax.swing.JTextField anchomilimetros1;
    private javax.swing.JTextField anchopaquete;
    private javax.swing.JTextField anchototalpulgada;
    private javax.swing.JTextField basexaltura;
    private javax.swing.JTextField cajaxpaleta;
    private javax.swing.JPanel caracteristicas;
    private javax.swing.JTextField categoriacaja;
    private javax.swing.JTextField cera;
    private javax.swing.JTextField cierre;
    private javax.swing.JTextField codigocliente;
    private javax.swing.JTextField codigoproducto;
    private javax.swing.JTextField colacorrugadora;
    private javax.swing.JTextField colaterminado;
    private javax.swing.JTextField color1;
    private javax.swing.JTextField color1gcmi;
    private javax.swing.JTextField color2;
    private javax.swing.JTextField color2gcmi;
    private javax.swing.JTextField color3;
    private javax.swing.JTextField color3gcmi;
    private javax.swing.JTextField color4;
    private javax.swing.JTextField color4gcmi;
    private javax.swing.JTextField color5;
    private javax.swing.JTextField color5gcmi;
    private javax.swing.JTextField color6;
    private javax.swing.JTextField color6gcmi;
    private javax.swing.JLabel componente;
    private javax.swing.JTextField componenteancho;
    private javax.swing.JTextField componenteancho1;
    private javax.swing.JTextField componentelargo;
    private javax.swing.JPanel dimenciones;
    private javax.swing.JTextField diseñadopor;
    private javax.swing.JTextField enfundado;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField flauta;
    private javax.swing.JTextField gapinferior;
    private javax.swing.JTextField gapinferior1;
    private javax.swing.JTextField gapsuperior;
    private javax.swing.JTextField gapsuperiormm;
    private javax.swing.JTextField grupo;
    private javax.swing.JTextField idarte;
    private javax.swing.JTextField idmuestra;
    private javax.swing.JLabel imagenprintmaster;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField largo;
    private javax.swing.JTextField largo1;
    private javax.swing.JTextField largomilimetro;
    private javax.swing.JTextField largomilimetro1;
    private javax.swing.JTextField largopaquete;
    private javax.swing.JTextField largototalpulgada;
    private javax.swing.JTextField nombrecliente;
    private javax.swing.JTextField numerotroquel;
    private javax.swing.JTextField panelsuperior;
    private javax.swing.JTextField panelsuperior1;
    private javax.swing.JTextField panelsuperior2;
    private javax.swing.JTextField papelexterno;
    private javax.swing.JTextField papelinterno;
    private javax.swing.JTextField personalizado;
    private javax.swing.JTextField plstificado;
    private javax.swing.JPanel reportearte;
    private javax.swing.JTextField resina;
    private javax.swing.JTextField sellotest;
    private javax.swing.JTextField test;
    private javax.swing.JTextField tipocaja;
    private javax.swing.JTextField unidadxpaquete;
    // End of variables declaration//GEN-END:variables
}
