/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author jpaula
 */
public class Printmaster extends javax.swing.JFrame {

    /**
     * Creates new form PM
     */
    public Printmaster() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cargarfrontal = new javax.swing.JToggleButton();
        cargartrasera = new javax.swing.JToggleButton();
        printmaster = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        codigoanterior = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        udxpaquetes = new javax.swing.JTextField();
        basexaltura = new javax.swing.JTextField();
        cxp = new javax.swing.JTextField();
        paletasxcont = new javax.swing.JTextField();
        largocomponente = new javax.swing.JTextField();
        anchocomponente = new javax.swing.JTextField();
        troquel = new javax.swing.JTextField();
        largopaquete = new javax.swing.JTextField();
        anchopaquete = new javax.swing.JTextField();
        altopaquete = new javax.swing.JTextField();
        imagentrasera = new javax.swing.JTextField();
        imagenfrontal = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        comentarios = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        colaterminado = new javax.swing.JComboBox<>();
        cierre = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        solicitud = new javax.swing.JTextField();
        grupo = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        cliente = new javax.swing.JTextField();
        producto = new javax.swing.JTextField();
        horizontal = new javax.swing.JRadioButton();
        veltical = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargarfrontal.setText("Cargar");
        jPanel1.add(cargarfrontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 460, 90, 25));

        cargartrasera.setText("Cargar");
        jPanel1.add(cargartrasera, new org.netbeans.lib.awtextra.AbsoluteConstraints(1068, 460, 90, 25));

        printmaster.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        printmaster.setForeground(new java.awt.Color(102, 102, 102));
        printmaster.setText("Print Master");
        jPanel1.add(printmaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 270, 70));

        logo.setBackground(new java.awt.Color(102, 102, 102));
        logo.setForeground(new java.awt.Color(102, 102, 102));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGO CARTONES full.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 31, 310, 100));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Codigo Anterior");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ud X Paquete BXA");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CXP");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 240, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Paletas X Cont.");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 240, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Largo");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 50, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ancho");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 60, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Troquel");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Largo        Ancho         Alto");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Paquetes");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("IMAGEN FRONTAL");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 470, -1, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("IMAGEN TRASERA");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 470, -1, -1));

        codigoanterior.setEditable(false);
        codigoanterior.setBackground(new java.awt.Color(204, 204, 204));
        codigoanterior.setForeground(new java.awt.Color(255, 255, 255));
        codigoanterior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(codigoanterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 160, 110, 25));

        fecha.setEditable(false);
        fecha.setBackground(new java.awt.Color(204, 204, 204));
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 160, 110, 25));

        udxpaquetes.setEditable(false);
        udxpaquetes.setBackground(new java.awt.Color(204, 204, 204));
        udxpaquetes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        udxpaquetes.setForeground(new java.awt.Color(255, 255, 255));
        udxpaquetes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(udxpaquetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 60, 25));

        basexaltura.setEditable(false);
        basexaltura.setBackground(new java.awt.Color(204, 204, 204));
        basexaltura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        basexaltura.setForeground(new java.awt.Color(255, 255, 255));
        basexaltura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(basexaltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 260, 60, 25));

        cxp.setEditable(false);
        cxp.setBackground(new java.awt.Color(204, 204, 204));
        cxp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cxp.setForeground(new java.awt.Color(255, 255, 255));
        cxp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(cxp, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, 60, 25));

        paletasxcont.setEditable(false);
        paletasxcont.setBackground(new java.awt.Color(204, 204, 204));
        paletasxcont.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        paletasxcont.setForeground(new java.awt.Color(255, 255, 255));
        paletasxcont.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(paletasxcont, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 260, 60, 25));

        largocomponente.setEditable(false);
        largocomponente.setBackground(new java.awt.Color(204, 204, 204));
        largocomponente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        largocomponente.setForeground(new java.awt.Color(255, 255, 255));
        largocomponente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        largocomponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largocomponenteActionPerformed(evt);
            }
        });
        jPanel1.add(largocomponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 70, 25));

        anchocomponente.setEditable(false);
        anchocomponente.setBackground(new java.awt.Color(204, 204, 204));
        anchocomponente.setForeground(new java.awt.Color(255, 255, 255));
        anchocomponente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(anchocomponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 70, 25));

        troquel.setEditable(false);
        troquel.setBackground(new java.awt.Color(204, 204, 204));
        troquel.setForeground(new java.awt.Color(255, 255, 255));
        troquel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(troquel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 120, 25));

        largopaquete.setEditable(false);
        largopaquete.setBackground(new java.awt.Color(204, 204, 204));
        largopaquete.setForeground(new java.awt.Color(255, 255, 255));
        largopaquete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(largopaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 330, 60, 25));

        anchopaquete.setEditable(false);
        anchopaquete.setBackground(new java.awt.Color(204, 204, 204));
        anchopaquete.setForeground(new java.awt.Color(255, 255, 255));
        anchopaquete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(anchopaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 330, 60, 25));

        altopaquete.setEditable(false);
        altopaquete.setBackground(new java.awt.Color(204, 204, 204));
        altopaquete.setForeground(new java.awt.Color(255, 255, 255));
        altopaquete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(altopaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 330, 60, 25));

        imagentrasera.setEditable(false);
        imagentrasera.setBackground(new java.awt.Color(255, 255, 255));
        imagentrasera.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(imagentrasera, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 550, 330));

        imagenfrontal.setEditable(false);
        imagenfrontal.setBackground(new java.awt.Color(255, 255, 255));
        imagenfrontal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(imagenfrontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 550, 330));

        jToggleButton2.setBackground(new java.awt.Color(102, 102, 102));
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar-button.png"))); // NOI18N
        jToggleButton2.setSelected(true);
        jToggleButton2.setBorder(null);
        jToggleButton2.setBorderPainted(false);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 830, 45, 45));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Comentarios");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        comentarios.setEditable(false);
        comentarios.setBackground(new java.awt.Color(204, 204, 204));
        comentarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comentarios.setForeground(new java.awt.Color(255, 255, 255));
        comentarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(comentarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 430, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cola Terminado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        colaterminado.setBackground(new java.awt.Color(255, 255, 255));
        colaterminado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        colaterminado.setForeground(new java.awt.Color(0, 0, 0));
        colaterminado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Especial", "No Lleva", " " }));
        colaterminado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(colaterminado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 130, 25));

        cierre.setBackground(new java.awt.Color(255, 255, 255));
        cierre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cierre.setForeground(new java.awt.Color(0, 0, 0));
        cierre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pegada", "Auto Armable", "Grapada", "No Lleva" }));
        cierre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(cierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 130, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cierre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 50, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Producto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cliente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 60, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Solicitud");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 70, 20));

        solicitud.setEditable(false);
        solicitud.setBackground(new java.awt.Color(204, 204, 204));
        solicitud.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        solicitud.setForeground(new java.awt.Color(255, 255, 255));
        solicitud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(solicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 180, 25));

        grupo.setEditable(false);
        grupo.setBackground(new java.awt.Color(204, 204, 204));
        grupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        grupo.setForeground(new java.awt.Color(255, 255, 255));
        grupo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 40, 25));

        codigo.setEditable(false);
        codigo.setBackground(new java.awt.Color(204, 204, 204));
        codigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigo.setForeground(new java.awt.Color(255, 255, 255));
        codigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 100, 25));

        cliente.setEditable(false);
        cliente.setBackground(new java.awt.Color(204, 204, 204));
        cliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cliente.setForeground(new java.awt.Color(255, 255, 255));
        cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 270, 25));

        producto.setEditable(false);
        producto.setBackground(new java.awt.Color(204, 204, 204));
        producto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        producto.setForeground(new java.awt.Color(255, 255, 255));
        producto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 430, 25));

        horizontal.setBackground(new java.awt.Color(102, 102, 102));
        horizontal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        horizontal.setForeground(new java.awt.Color(255, 255, 255));
        horizontal.setText("Horizontal");
        horizontal.setBorder(null);
        jPanel1.add(horizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        veltical.setBackground(new java.awt.Color(102, 102, 102));
        veltical.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        veltical.setForeground(new java.awt.Color(255, 255, 255));
        veltical.setText("Vertical");
        veltical.setBorder(null);
        jPanel1.add(veltical, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void largocomponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largocomponenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largocomponenteActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
       Preprensa preprensa = new Preprensa();
           preprensa.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Printmaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Printmaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Printmaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Printmaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Printmaster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altopaquete;
    private javax.swing.JTextField anchocomponente;
    private javax.swing.JTextField anchopaquete;
    private javax.swing.JTextField basexaltura;
    private javax.swing.JToggleButton cargarfrontal;
    private javax.swing.JToggleButton cargartrasera;
    private javax.swing.JComboBox<String> cierre;
    private javax.swing.JTextField cliente;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField codigoanterior;
    private javax.swing.JComboBox<String> colaterminado;
    private javax.swing.JTextField comentarios;
    private javax.swing.JTextField cxp;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField grupo;
    private javax.swing.JRadioButton horizontal;
    private javax.swing.JTextField imagenfrontal;
    private javax.swing.JTextField imagentrasera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextField largocomponente;
    private javax.swing.JTextField largopaquete;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField paletasxcont;
    private javax.swing.JLabel printmaster;
    private javax.swing.JTextField producto;
    private javax.swing.JTextField solicitud;
    private javax.swing.JTextField troquel;
    private javax.swing.JTextField udxpaquetes;
    private javax.swing.JRadioButton veltical;
    // End of variables declaration//GEN-END:variables
}
