/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaventas;

import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Conexion.ClassConection;
/**
 *
 * @author avalos
 */
public class ConsultaBoleto extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaBoleto
     */
    ClassConection conectar=new ClassConection();
     Connection cn;
   CallableStatement cts;
   ResultSet r;
    public ConsultaBoleto() {
        initComponents();
        jTextField1.setEnabled(false);
           cn=conectar.conecion();
          cargar();
    }
    
     private void cargar(){
        
         DefaultTableModel tabla= new DefaultTableModel();
       try{
         tabla.addColumn("N° BOLETA");
       tabla.addColumn("FECHA");
       tabla.addColumn("CLIENTE");
       tabla.addColumn("TOTAL A PAGAR");
         cts=cn.prepareCall("{call BUSCARBOLETOS}");
       r=cts.executeQuery();
       while (r.next()){
       Object dato[]=new  Object[4];
       for (int i=0; i<4; i++){
           dato[i]=r.getString(i+1);

       }
       tabla.addRow(dato);
       }
       this.jTable1.setModel(tabla);
   
       }catch (Exception e){}}
        
 
public void mostrarDetalleboleto(){
     MostrarBoleta mb = new MostrarBoleta();
                
         try {
            
       int row=jTable1.getSelectedRow();
         String idB=jTable1.getValueAt(row, 0).toString();
         String fecha=jTable1.getValueAt(row, 1).toString();
        String idcli=jTable1.getValueAt(row, 2).toString();
        String pret=jTable1.getValueAt(row,3).toString();
        DefaultTableModel tabla = (DefaultTableModel) MostrarBoleta.jtableDetalle.getModel();
        try
       {
        cts=cn.prepareCall("{call MostrarDEtalleBoleta(?)}");
            cts.setString(1, idB);
            r=cts.executeQuery();
       while (r.next()){
       Object dato[]=new  Object[5];
       for (int i=0; i<5; i++){
           dato[i]=r.getString(i+1);

       }
       tabla.addRow(dato);
       }
     MostrarBoleta.jtableDetalle.setModel(tabla);
    MostrarBoleta.lbl_nBOLETA.setText(idB);
    MostrarBoleta.JLB_codCliente.setText(idcli);
    MostrarBoleta.lbl_Fecha.setText(fecha);
    MostrarBoleta.jtex_preto.setText(pret);
  }catch (Exception e){}
        } catch (Exception ex) {
        
          Logger.getLogger(Factura.class.getName()).log(Level.SEVERE, null, ex);
        }
           SistemaV.jDesktopPane1.add(mb);
        mb.toFront();
        mb.setLocation(50,10);
        mb.setVisible(true);
        this.dispose();
       }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jR_boleta = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jR_fecha = new javax.swing.JRadioButton();
        jR_mosTodo = new javax.swing.JRadioButton();

        jMenuItem1.setText("Mostrar detalle de Boleta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Eliminar Boleta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(jR_boleta);
        jR_boleta.setText("Mostrar por N° Boleta:");
        jR_boleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR_boletaActionPerformed(evt);
            }
        });

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jR_fecha);
        jR_fecha.setText("Mostrar por Fecha:");
        jR_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR_fechaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jR_mosTodo);
        jR_mosTodo.setSelected(true);
        jR_mosTodo.setText("Mostrar todas las facturas.");
        jR_mosTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR_mosTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jR_mosTodo)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jR_fecha)
                            .addComponent(jR_boleta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(152, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jR_boleta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jR_fecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jR_mosTodo))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jR_boletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR_boletaActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField1.setEnabled(true);
        jTextField1.requestFocus();
    }//GEN-LAST:event_jR_boletaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String X = jTextField1.getText();

        if (jR_boleta.isSelected() == true) {
            jTextField1.setText("");
            jTextField1.setEnabled(true);
            jTextField1.requestFocus();
            DefaultTableModel tabla = new DefaultTableModel();
            try {
                 tabla.addColumn("N° BOLETA");
       tabla.addColumn("FECHA");
       tabla.addColumn("CLIENTE");
       tabla.addColumn("TOTAL A PAGAR");
                cts = cn.prepareCall("{call BUSCARBOLETONB(?)}");
                cts.setString(1, X);
                r = cts.executeQuery();
                while (r.next()) {
                    Object dato[] = new Object[4];
                    for (int i = 0; i < 4; i++) {
                        dato[i] = r.getString(i + 1);

                    }
                    tabla.addRow(dato);
                }
                this.jTable1.setModel(tabla);
            } catch (Exception e) {
            }

        } else if (jR_fecha.isSelected() == true) {
            jTextField1.setText("");
            jTextField1.setEnabled(true);
            jTextField1.requestFocus();
            DefaultTableModel tabla = new DefaultTableModel();
            try {
                 tabla.addColumn("N° BOLETA");
                 tabla.addColumn("FECHA");
                 tabla.addColumn("CLIENTE");
                 tabla.addColumn("TOTAL A PAGAR");
                cts = cn.prepareCall("{call BUSCARboletaFECHA(?)}");
                cts.setString(1, X);
                r = cts.executeQuery();
                while (r.next()) {
                    Object dato[] = new Object[4];
                    for (int i = 0; i < 4; i++) {
                        dato[i] = r.getString(i + 1);

                    }
                    tabla.addRow(dato);
                }
                this.jTable1.setModel(tabla);
            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jR_mosTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR_mosTodoActionPerformed
        // TODO add your handling code here:
        cargar();
        jTextField1.setText("");
        jTextField1.setEnabled(false);

    }//GEN-LAST:event_jR_mosTodoActionPerformed

    private void jR_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR_fechaActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField1.setEnabled(true);
        jTextField1.requestFocus();
    }//GEN-LAST:event_jR_fechaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        mostrarDetalleboleto();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
                 
        try {
            int row=jTable1.getSelectedRow();
         String idb=jTable1.getValueAt(row, 0).toString();
            cts=cn.prepareCall("{ call eliminarboletos(?)}");
            cts.setString(1, idb);
            int rpta=cts.executeUpdate();

            if(rpta==1){
            JOptionPane.showMessageDialog(this, "Boleta Eliminado","Aviso",JOptionPane.INFORMATION_MESSAGE);
          //ahora obtenemos la fila selccionada
       if(row<0){
            // no se puede eliminar
            JOptionPane.showMessageDialog(this,"Tabla vacia o no ha seleccionado uan fila.");
        }else {
          // la eliminamos del modelo:
        modelo.removeRow(row);
        }
        
            
                    }else {
             JOptionPane.showMessageDialog(this, "Boleta No Eliminado","Aviso",JOptionPane.INFORMATION_MESSAGE);

            }

        } catch (SQLException | HeadlessException e) {JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jR_boleta;
    private javax.swing.JRadioButton jR_fecha;
    private javax.swing.JRadioButton jR_mosTodo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
